Name: cloudmind-content
ListenOn: 0.0.0.0:2002
Mode: dev
Elasticsearch:
  Addresses:
    - http://118.89.172.143:9200
  Username: elastic
  Password: 5201314LS
##Monitoring
Prometheus:
  Host: 0.0.0.0
  Port: 4002
  Path: /metrics

##Link Tracking
Telemetry:
  Name: content
  Endpoint: http://118.89.172.143:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

Log:
  ServiceName: content
  Level: info
  Mode: console
  Encoding: plain

Redis:
  Host: 118.89.172.143:6379
  Type: node
  Pass: 5201314LS
  Key: ""

Mongo:
  Url: mongodb://root:123@118.89.172.143:27017,192.144.226.115:27017,134.175.180.149:27017/?replSet=rs0
  DB: cloudmind_content

Cache:
  - host: 118.89.172.143:6379
    type: node
    pass: 5201314LS
EtcdConf:
  Hosts:
    - 118.89.172.143:2379
    - 192.144.226.115:2379
    - 134.175.180.149:2379