Name: cloudmind.content
ListenOn: 0.0.0.0:8080
Mode: dev

Prometheus:
  Host: 0.0.0.0
  Port: 4003
  Path: /metrics

Log:
  Encoding: json
  Level: debug
  Stat: false

Mongo:
  URL: mongodb+srv://root:FhfzRPcLfF@mongodb-headless.mongodb.svc.cluster.local/?tls=false
  DB: cloudmind_content

CacheConf:
  - Host: redis-master.redis:6379

Elasticsearch:
  Addresses:
    - https://es-elasticsearch.elasticsearch:9200
  Username: elastic
  Password: cloudmind

Telemetry:
  Endpoint: http://jaeger-collector.istio-system:14268/api/traces

Redis:
  Host: redis-master.redis:6379