// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/CloudStriver/cloudmind-content/biz/adaptor"
	"github.com/CloudStriver/cloudmind-content/biz/application/service"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/config"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/mapper/coupon"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/mapper/file"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/mapper/order"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/mapper/post"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/mapper/product"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/mapper/sharefile"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/mapper/user"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/mapper/zone"
	"github.com/CloudStriver/cloudmind-content/biz/infrastructure/stores/redis"
)

// Injectors from wire.go:

func NewContentServerImpl() (*adaptor.ContentServerImpl, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	iMongoMapper := file.NewMongoMapper(configConfig)
	iFileEsMapper := file.NewEsMapper(configConfig)
	sharefileIMongoMapper := sharefile.NewMongoMapper(configConfig)
	fileService := &service.FileService{
		FileMongoMapper:      iMongoMapper,
		FileEsMapper:         iFileEsMapper,
		ShareFileMongoMapper: sharefileIMongoMapper,
	}
	iPostMongoMapper := post.NewMongoMapper(configConfig)
	iEsMapper := post.NewEsMapper(configConfig)
	redisRedis := redis.NewRedis(configConfig)
	postService := &service.PostService{
		Config:          configConfig,
		PostMongoMapper: iPostMongoMapper,
		PostEsMapper:    iEsMapper,
		Redis:           redisRedis,
	}
	zoneIMongoMapper := zone.NewMongoMapper(configConfig)
	zoneService := &service.ZoneService{
		ZoneMongoMapper: zoneIMongoMapper,
	}
	iUserMongoMapper := user.NewMongoMapper(configConfig)
	iUserEsMapper := user.NewEsMapper(configConfig)
	userService := &service.UserService{
		Config:          configConfig,
		UserMongoMapper: iUserMongoMapper,
		UserEsMapper:    iUserEsMapper,
		Redis:           redisRedis,
	}
	iProductMongoMapper := product.NewMongoMapper(configConfig)
	productIEsMapper := product.NewEsMapper(configConfig)
	productService := &service.ProductService{
		Config:             configConfig,
		ProductMongoMapper: iProductMongoMapper,
		ProductEsMapper:    productIEsMapper,
		Redis:              redisRedis,
	}
	iCouponMongoMapper := coupon.NewMongoMapper(configConfig)
	couponIEsMapper := coupon.NewEsMapper(configConfig)
	couponService := &service.CouponService{
		Config:            configConfig,
		CouponMongoMapper: iCouponMongoMapper,
		CouponEsMapper:    couponIEsMapper,
		Redis:             redisRedis,
	}
	iOrderMongoMapper := order.NewMongoMapper(configConfig)
	orderIEsMapper := order.NewEsMapper(configConfig)
	orderService := &service.OrderService{
		Config:           configConfig,
		OrderMongoMapper: iOrderMongoMapper,
		OrderEsMapper:    orderIEsMapper,
		Redis:            redisRedis,
	}
	contentServerImpl := &adaptor.ContentServerImpl{
		Config:         configConfig,
		FileService:    fileService,
		PostService:    postService,
		ZoneService:    zoneService,
		UserService:    userService,
		ProductService: productService,
		CouponService:  couponService,
		OrderService:   orderService,
	}
	return contentServerImpl, nil
}
